services:
  postgres:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diet_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
